[package]
name = "imgmng"
version = "0.1.0"
edition = "2021"
authors = ["LucasHazardous"]
repository = "https://github.com/LucasHazardous/imgmng"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
image = "0.24.5"
